export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
  
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    GET_GAMES_REQUEST: 'GET_GAMES_REQUEST',
    GET_GAMES_SUCCESS: 'GET_GAMES_SUCCESS',
    GET_GAMES_FAILURE: 'GET_GAMES_FAILURE',

    POST_GAMES_REQUEST: 'POST_GAMES_REQUEST',
    POST_GAMES_SUCCESS: 'POST_GAMES_SUCCESS',
    POST_GAMES_FAILURE: 'POST_GAMES_FAILURE',
  
    LOGOUT: 'USERS_LOGOUT',
  
    SET_USERNAME_NAVBAR: 'SET_USERNAME_NAVBAR',
    SET_USER_DATA: 'SET_USER_DATA',
    DELETE_USER_DATA: 'DELETE_USER_DATA',

    SET_GAMES_DATA: 'SET_GAMES_DATA',
    DELETE_GAMES_DATA: 'DELETE_GAMES_DATA',
  };


export const attackConstants = {
  ATTACK: "ATTACK",
  BLAST: "BLAST",
  HEAL: "HEAL",
  GIVEUP: "GIVEUP",

  SET_HEALTH: "SET_HEALTH",
  RESET_HEALTH: "RESET_HEALTH",
  SET_GAME_STATUS: "SET_GAME_STATUS",
}